applications/urls.py
from django.urls import path
from . import views
from django.contrib import admin
from .views import apply, application_success
from django.views.generic import TemplateView
from .views import user_added

urlpatterns = [
    path('base/', views.base_view, name='base'),
    path('', views.index, name='index'),
    path('login/', views.login_site, name='login'),
    path('register/', views.registration_page, name= 'registration_page'),
    path('logout/', views.logout_site, name='logout'),
    path('apply/', views.apply, name='apply'),
    path('apply/', views.submit_application, name='apply'),
    path('apply/success/', application_success, name='application_success'),
    path('application_exists/', views.application_exists, name='application_exists'),
    path('application_list/', views.applications_list, name='applications_list'),
    path('application_detail/<int:pk>/', views.application_detail, name='application_detail'),
    path('update_application_status/<int:pk>/', views.update_application_status, name='update_application_status'),
    path('custom_user_created/', views.custom_user_created, name='custom_user_created'),
    path('players/', views.player_list, name='player_list'),
    path('info/', views.server_info, name='server_info'),
    path('rules/', views.rules_page, name='rules'),
    path('application/delete/<int:pk>/', views.delete_application, name='delete_application'),
    path('minecraftuser/add/', views.add_minecraft_user, name='add_minecraft_user'),
    path('user_added/', user_added, name='user_added'),
    path('edit/<int:player_id>/', views.edit_player, name='edit_player'),
    path('player_list_adm/<int:player_id>/delete_player/', views.delete_player, name='delete_player'),
    path('player_list_adm/<int:player_id>/confirm_delete/', views.confirm_delete, name='confirm_delete'),
    path('player_list_adm', views.player_list_adm, name='player_list_adm'),
    path('news/', views.news_list, name='news_list'),
    path('news/<int:pk>/', views.news_detail, name='news_detail'),
    path('news/add/', views.create_news, name='create_news'),
    path('welcome/', views.welcome, name='welcome'),
    path('event_list/', views.event_list, name='event_list'),
    path('add_event/', views.add_event, name='add_event'),
    path('edit_event/<int:pk>/', views.edit_event, name='edit_event'),
    path('event/<int:event_id>/delete/', views.delete_event, name='delete_event'),
    path('event_delete/<int:pk>/', views.delete_event, name='delete_event'),
    path('map/', views.map_view, name='map'),
    path('chat/', views.chat, name='chat'),
    path('send_message/', views.send_message, name='send_message'),
    path('get_messages/', views.get_messages, name='get_messages'),
]

myserverproject/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/models.py
from django.db import models
from django.contrib import admin
from django.contrib.auth.models import AbstractUser, Group, Permission
from django.contrib.auth.models import User
import uuid
# Create your models here.

class Prefix(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Status(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class CustomUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    nickname = models.CharField(max_length=100)
    prefix = models.ForeignKey(Prefix, on_delete=models.SET_NULL, null=True, blank=True)
    status = models.ForeignKey(Status, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return self.user.username     
    # Получение существующего пользователя
try:
    existing_user = User.objects.get(username='existing_user')
except User.DoesNotExist:
    print("Пользователь с указанным именем не существует.")
else:
    # Создание нового объекта CustomUser с использованием данных существующего пользователя
    custom_user = CustomUser.objects.create(
        user=existing_user,
        nickname=existing_user.username,  # Используйте имя пользователя в качестве nickname или любое другое значение
        # Другие поля модели CustomUser
    )

    # Сохранение объекта CustomUser
    custom_user.save()

    class Meta:
        model = CustomUser
        fields = ['discord_link']



class DiscordInvitation(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    invite_link = models.CharField(max_length=100, unique=True)

    @classmethod
    def generate_invite_link(cls):
        return str(uuid.uuid4())
    


class MinecraftUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    nickname = models.CharField(max_length=100)
    prefix = models.ForeignKey(Prefix, on_delete=models.SET_NULL, null=True, blank=True)
    status = models.ForeignKey(Status, on_delete=models.SET_NULL, null=True, blank=True)


    def __str__(self):
        return self.user.username
    
    

class News(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    content = models.TextField()
    image = models.ImageField(upload_to='news_images/')
    date_published = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True)



    def __str__(self):
        return self.title
    

class ChatMessage(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    message = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user.username} - {self.timestamp}'



class Application(models.Model):

    STATUS_CHOICES = [
        ('pending', 'Ожидание'),
        ('rejected', 'Отклонено'),
        ('approved', 'Одобрено'),
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    nickname = models.CharField(max_length=100)
    age = models.IntegerField()
    source = models.CharField(max_length=100)
    previous_projects = models.TextField()
    activities = models.TextField()
    read_rules = models.TextField()
    communication_style = models.CharField(max_length=100)
    participate_in_storyline = models.TextField()
    status = models.CharField(max_length=100, choices=STATUS_CHOICES, default='pending')
    prefix = models.ForeignKey(Prefix, on_delete=models.SET_NULL, null=True, blank=True)
    discord_link = models.URLField(blank=True)

    def __str__(self):
        return f'Application {self.id} by {self.user.username}'




class ServerEvent(models.Model):
    STATUS_CHOICES = (
        ('upcoming', 'Ближайший'),
        ('current', 'Текущий'),
        ('past', 'Прошедший'),
    )
    
    title = models.CharField(max_length=100)
    description = models.TextField()
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='upcoming')
    date = models.DateTimeField()
    organizer = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

applications/views.py
from django.shortcuts import render, redirect, get_object_or_404    
from django.contrib.auth import authenticate, login, logout
from django.core.paginator import Paginator, EmptyPage
from .forms import ApplicationForm
from .models import Application
from django.http import JsonResponse
from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from .models import MinecraftUser, Prefix, Status
from .models import DiscordInvitation
import uuid
from .models import Prefix, Status
from .forms import MinecraftUserForm
from .models import News
from .forms import NewsForm
from .models import ServerEvent
from .forms import ServerEventForm
from django.http import HttpResponseBadRequest
from .models import ChatMessage




@login_required
def base_view(request):
    if request.user.is_authenticated:
        return render(request, 'base.html')
    return redirect('index')

def index(request):
    if not request.user.is_authenticated:
        return redirect('welcome')  # Перенаправляем неавторизованных пользователей на страницу приветствия
    else:
        return render(request, 'index.html')


def registration_page(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect('index')  # Замените 'index.html' на URL вашей главной страницы
    else:
        form = UserCreationForm()
    return render(request, 'register.html', {'form': form})

# Авторизация
def login_site(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('index')
        else:
            return render(request, 'login.html', {'error_message': 'Неверное имя пользователя или пароль.'})
    return render(request, 'login.html')

@login_required
def logout_site(request):
    logout(request)
    return redirect('welcome')


def apply(request):
    existing_application = Application.objects.filter(user=request.user).first()
    
    # Проверяем, существует ли заявка для текущего пользователя
    if existing_application:
        status = existing_application.get_status_display()
        
        # Если заявка уже существует, и ее статус "Одобрено", создаем CustomUser
        if existing_application.status == 'approved':
            # Получаем или создаем CustomUser
            custom_user, created = get_user_model().objects.get_or_create(username=request.user.username)
            custom_user.nickname = existing_application.nickname
            custom_user.discord_link = existing_application.discord_link  # Добавляем сохранение ссылки на Discord
            custom_user.save()
            return render(request, 'custom_user_created.html', {'custom_user': custom_user})
        else:
            return render(request, 'application_exists.html', {'status': status})
    else:
        if request.method == 'POST':
            form = ApplicationForm(request.POST)
            if form.is_valid():
                application = form.save(commit=False)
                application.user = request.user
                application.save()
                return render(request, 'application_success.html')
        else:
            form = ApplicationForm()
        return render(request, 'apply.html', {'form': form})
    
def submit_application(request):
    if request.method == 'POST':
        form = ApplicationForm(request.POST)
        if form.is_valid():
            form.save()
            # После успешной отправки заявки редиректим пользователя на нужную страницу, например, на главную
            return redirect('')
    else:
        form = ApplicationForm()
    return render(request, '', {'form': form})


@login_required
def application_success(request):
    # Проверяем, существует ли запись DiscordInvitation для текущего пользователя
    return render(request, 'application_success.html')



def applications_list(request):
    all_applications = Application.objects.all()
    paginator = Paginator(all_applications, 10)  # Пагинация по 10 записей на страницу

    page_number = request.GET.get('page', 1)  # Установка значения по умолчанию на 1, если параметр 'page' отсутствует
    try:
        applications = paginator.page(page_number)
    except EmptyPage:
        applications = paginator.page(paginator.num_pages)

    return render(request, 'applications_list.html', {'applications': applications})



def application_detail(request, pk):
    application = Application.objects.get(pk=pk)
    return render(request, 'application_detail.html', {'application': application})




def update_application_status(request, pk):
    # Получаем объект заявки или выводим ошибку 404, если объект не найден
    application = get_object_or_404(Application, pk=pk)

    if request.method == 'POST':
        # Обрабатываем данные формы, отправленные методом POST
        new_status = request.POST.get('status')
        application.status = new_status
        application.save()
        # Перенаправляем пользователя обратно на страницу с деталями заявки
        return redirect('application_detail', pk=pk)
    else:
        # Если запрос не методом POST, просто показываем шаблон с формой для изменения статуса
        return render(request, 'update_application_status.html', {'application': application})




def application_exists(request):
    try:
        # Получаем текущего пользователя
        user = request.user
        # Пытаемся найти заявку пользователя
        application = Application.objects.get(user=user)
        # Получаем отображаемое значение статуса заявки
        status = application.get_status_display()
        return render(request, 'application_exists.html', {'status': status})
    except Application.DoesNotExist:
        # Если заявка не найдена, возвращаем пустой контекст
        return render(request, 'application_exists.html', {})
    



def profile_view(request, user_id):
    # Получаем пользователя по его ID
    user = User.objects.get(pk=user_id)
    if hasattr(user, 'customuser'):
        custom_user = user.customuser
    else:
        custom_user = None
    return render(request, 'profile.html', {'user': user, 'custom_user': custom_user})  

def custom_user_created(request):
    if request.method == 'POST':
        
        return redirect('application_success')
    else:
        
        try:
            discord_invitation = DiscordInvitation.objects.get(user=request.user)
        except DiscordInvitation.DoesNotExist:
            invite_link = DiscordInvitation.generate_invite_link()
            discord_invitation = DiscordInvitation.objects.create(user=request.user, invite_link=invite_link)

        return render(request, 'custom_user_created.html', {'invite_link': discord_invitation.invite_link})


def player_list(request):
    search_query = request.GET.get('search', '')
    if search_query:
        players = MinecraftUser.objects.filter(nickname__icontains=search_query)
    else:
        players = MinecraftUser.objects.all()
    return render(request, 'player_list.html', {'players': players})

def server_info(request):

    server_ip = "bokenori.online"


    context = {
        'server_ip': server_ip,
    }
    return render(request, 'info.html', context)


def rules_page(request):
    return render(request, 'rules.html')


def delete_application(request, pk):
    application = get_object_or_404(Application, pk=pk)
    if request.method == 'POST':
        application.delete()
        return redirect('applications_list')
    return render(request, 'application_delete.html', {'application': application})


def add_minecraft_user(request):
    users = User.objects.all()  
    prefixes = Prefix.objects.all() 
    statuses = Status.objects.all() 

    if request.method == 'POST':
        form = MinecraftUserForm(request.POST)
        if form.is_valid():
            selected_user_id = form.cleaned_data['user'].id
            selected_user = User.objects.get(id=selected_user_id)
            if not MinecraftUser.objects.filter(user=selected_user).exists():
                minecraft_user = form.save(commit=False)
                minecraft_user.user = selected_user
                minecraft_user.save()
                return redirect('user_added')
            else:
                form.add_error(None, "This user already exists.")
    else:
        form = MinecraftUserForm()

    return render(request, 'add_minecraft_user.html', {'form': form, 'users': users, 'prefixes': prefixes, 'statuses': statuses})

def user_added(request):
    users = MinecraftUser.objects.all()
    return render(request, 'added.html', {'users': users})


def player_list_adm(request):
    players = MinecraftUser.objects.all()
    return render(request, 'player_list_adm.html', {'players': players})


def edit_player(request, player_id):
    users = User.objects.all() 
    prefixes = Prefix.objects.all() 
    statuses = Status.objects.all() 
    
    player = get_object_or_404(MinecraftUser, id=player_id)
    if request.method == 'POST':
        form = MinecraftUserForm(request.POST, instance=player)
        if form.is_valid():
            form.save()
            return redirect('player_list_adm')
    else:
        form = MinecraftUserForm(instance=player)

applications/templates/added.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="card mt-4">
        <div class="card-body">
            <h1 class="card-title">Пользователь добавлен!</h1>
            <p>Пользователь успешно добавлен в систему.</p>
        </div>
    </div>
</div>
{% endblock %}

applications/templates/application_success.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <h3 class="card-title text-center mb-4">Заявка успешно отправлена!</h3>
                    <p class="card-text text-center">Ваша заявка успешно отправлена. Мы рассмотрим её в ближайшее время. Обычно это занимает не более 5 минут.</p>
                    <div class="text-center">
                        <a href="{% url 'apply' %}" class="btn btn-primary">Вернуться</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

applications/templates/apply.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Submit Application</title>
</head>
<body>
    <div class="new-users">
        <h2>Заявка на сервер</h2>
        <div class="user-list">
          <form method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="nickname">Ваш игровой Ник-Нейм</label>
                <input type="text" id="nickname" name="nickname" class="form-control" placeholder="Ник-Нейм" required>
            </div>
            <div class="form-group">
                <label for="age">Возраст</label>
                <input type="number" id="age" name="age" class="form-control" placeholder="Возраст" required>
            </div>
            <div class="form-group">
                <label for="source">Из какого источника узнали о проекте</label>
                <input type="text" id="source" name="source" class="form-control" placeholder="Источник" required>
            </div>
            <div class="form-group">
                <label for="previous_projects">На каких проектах вы участвовали до этого? Из-за чего вы ушли оттуда?</label>
                <input type="text" id="previous_projects" name="previous_projects" class="form-control" placeholder="Предыдущие проекты" required>
            </div>
            <div class="form-group">
                <label for="activities">Что вы обычно делаете на таких серверах? Чем вы планируете заниматься здесь?</label>
                <input type="text" id="activities" name="activities" class="form-control" placeholder="Активность" required>
            </div>
            <div class="form-group">
                <label for="read_rules">Тщательно ли вы читали правила? Готовы ли вы соблюдать их?</label>
                <input type="text" id="read_rules" name="read_rules" class="form-control" placeholder="Правила" required>
            </div>
            <div class="form-group">
                <label for="communication_style">Вы коммуникабельный человек? Какой стиль игры вы предпочитаете? (Одиночный, командный)</label>
                <input type="text" id="communication_style" name="communication_style" class="form-control" placeholder="Стиль игры" required>
            </div>
            <div class="form-group">
                <label for="participate_in_storyline">Хотели бы вы участвовать в сюжетной линии проекта?</label>
                <input type="text" id="participate_in_storyline" name="participate_in_storyline" class="form-control" placeholder="Сюжет">
            </div>
            <button type="submit" class="btn btn-primary">Отправить</button>
        </form>
    </form>





<!-- Modal -->
<div class="modal fade" id="applicationModal" tabindex="-1" aria-labelledby="applicationModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="applicationModalLabel">Ошибка отправки заявки</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          Вы уже отправили заявку. Пожалуйста, дождитесь ответа на предыдущую заявку.
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
        </div>
      </div>
    </div>
  </div>
  
  {% if already_submitted %}
  <script>
    // Открываем модальное окно, если пользователь уже отправил заявку
    window.onload = function() {
      var applicationModal = new bootstrap.Modal(document.getElementById('applicationModal'));
      applicationModal.show();
    };
  </script>
  {% endif %}
</body>
</html>
{% endblock %}

applications/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Главная{% endblock %}</title>
 
    <!-- Здесь вы можете подключить ваши статические файлы CSS, JavaScript и другие -->

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons+Sharp" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Geologica:wght@100..900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <link rel="icon" type="image/png" href="{% static 'images/image.png' %}">

</head>
<body>

    <div class="container1">
        <div class="sakura"><span></span><span></span><span></span><span></span>
            <span></span><span></span><span></span><span></span><span></span>
            <span></span><span></span><span></span><span></span><span></span>
            <span></span><span></span><span></span><span></span><span></span>
            <span></span><span></span><span></span><span></span><span></span>
            <span></span><span></span><span></span><span></span><span></span>
            <span></span><span></span><span></span><span></span><span></span>
            <span></span><span></span><span></span><span></span><span></span>
            <span></span><span></span><span></span><span></span><span></span>
            <span></span><span></span><span></span><span></span><span></span>
        </div>
    </div>

    <div class="container-custom">
        <!-- Sidebar Section -->
        <aside>
            <div class="toggle">
                <div class="logo-custom">
                    <h2>Boke<span class="danger">Nori </span></h2>
                </div>
                <div class="close" id="close-btn">
                    <span class="material-icons-sharp">
                        close
                    </span>
                </div>
            </div>


        

                <!-- Right Section -->
   

            

            <div class="sidebar-custom">
                <a href="{% url 'index' %}" {% if request.path == '/' %} class="active" {% endif %}>
                    <span class="material-icons-sharp">
                        dashboard
                    </span>
                    <h3>Главная</h3>
                </a>
 
                <a href="{% url 'rules' %}" {% if request.path == '/rules/' %} class="active" {% endif %} >
                    <span class="material-symbols-outlined">
                        menu_book
                        </span>
                    <h3>Правила</h3>
                </a>
                    <a href="{% url 'apply' %}"  {% if request.path == '/apply/' %} class="active" {% endif %}>
                        <span class="material-icons-sharp">
                            <i class="fa-solid fa-book"></i>
                        </span>
                        <h3>Заявка</h3>
                    </a>

                    <a href="{% url 'news_list' %}" {% if request.path == '/news/' %} class="active" {% endif %}>
                        <span class="material-symbols-outlined">
                            newsmode
                            </span>
                        <h3>Новости</h3>
                        </a>
                    {% if user.minecraftuser %}
                  
                    <a href="{% url 'server_info' %}" {% if request.path == '/info/' %} class="active" {% endif %}>
                        <span class="material-symbols-outlined">
                            info
                            </span>
                        <h3>Информация</h3>
                    </a>
                    <a href="{% url 'event_list' %}">
                    <span class="material-symbols-outlined">
                        brand_awareness
                        </span>
                        <h3>
                            Ивенты
                        </h3>
                    </a>
                    <a href="{% url 'player_list' %}" {% if request.path == '/players/' %} class="active" {% endif %} >
                        <span class="material-icons-sharp">
                            person
                        </span>
                        <h3>Список игроков</h3>
                    </a>

                    <a href="{% url 'map' %}">
                    <span class="material-symbols-outlined">
                        map
                        </span>
                        <h3>Карта</h3>
                    </a>

                     {% else %}
                    {% endif %}
                    {% if user.is_staff %}
                    <a href="">
                        <h3>===ADM===</h3>
                    </a>

                    <a href="{% url 'applications_list' %}">
                        <span class="material-symbols-outlined">
                            receipt_long
                            </span>
                        <h3>Список заявок</h3>
                    </a>
                    

                    <a href="{% url 'add_minecraft_user' %}">
                        <span class="material-symbols-outlined">
                            person_add
                            </span>
                            <h3>Добоавить пользователя</h3>
                    </a>
                    
<a href="{% url 'player_list_adm' %}">
    <span class="material-symbols-outlined">
        group
        </span>
        <h3>Управление
         пользователямя
        </h3>
</a>
                    
<a href="{% url 'create_news' %}">
    <span class="material-symbols-outlined">
        edit_calendar
        </span>
    <h3>Создать новость</h3>
</a>


{% endif %}


                    <a href="{% url 'logout' %}">
                        <span class="material-icons-sharp">
                            logout
                        </span>
                        <h3>Выйти из акк</h3>
                    </a>
                </div>



          

    

    </aside>
        




        <main>


                
            {% block content %}  {% endblock %}

 
        </main>



        <div class="right-section-custom">
            <div class="nav-custom">
                <button id="menu-btn">
                    <span class="material-icons-sharp">
                        menu
                    </span>
                </button>
                <div class="dark-mode">
                    <span class="material-icons-sharp active">
                        light_mode
                    </span>
                    <span class="material-icons-sharp">
                        dark_mode
                    </span>
                </div>
                <div class="profile">
                    <div class="info">
                        <p>Привет, <strong>{{ user.username }}</strong></p>
                        <small class="text-muted"></small>
                    </div>
                </div>
    
            </div>
        





        <script src="{% static 'js/script.js' %}"></script>
        <script src="{% static 'js/index.js' %}"></script>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://kit.fontawesome.com/af02ed48ba.js" crossorigin="anonymous"></script>
        <!-- jQuery и Bootstrap JS (подключите их, если необходимо) -->
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.3/dist/umd/popper.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

applications/templates/edit_event.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h1 class="mt-5">Редактировать событие</h1>
    <form method="post" class="mt-4">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_title" class="font-weight-bold">Название</label>
            {{ form.title }}
        </div>
        <div class="form-group">
            <label for="id_description" class="font-weight-bold">Описание</label>
            {{ form.description }}
        </div>
        <div class="form-group">
            <label for="id_date" class="font-weight-bold">Дата</label>
            {{ form.date }}
        </div>
        <div class="form-group">
            <label for="id_status" class="font-weight-bold">Статус</label>
            {{ form.status }}
        </div>
        <button type="submit" class="btn btn-primary mt-3">Сохранить</button>
        <a href="{% url 'delete_event' pk=event.pk %}" class="btn btn-danger mt-3 ml-2">Удалить</a>
    </form>
</div>
{% endblock %}